### ISSUE TITLE
Lazy loading a bean that is already in the cache and is dirty incorrectly resets EntityBeanIntercept state

### ISSUE THREAD

**Issue by jokester01au** [ebean-orm/avaje-ebeanorm#648] opened 2016-04-13 03:02 UTC
```
@Entity
public class Customer {
    @OneToMany(fetch = LAZY)
    public Set<Order> orders;
}

@Entity
public class Order {
      public String aValue;
}

Order o = new Order();
Customer c = new Customer();
c.orders = new HashSet<>();
c.orders.add(o);
o.save();
c.save();

Order o2 = Ebean.find(Order.class).findIterate().next();
o2.aValue = "foo";
Customer c2 = Ebean.find(Customer.class).findIterate().next();
c2.orders.add(new Order());
o2.save(); // does nothing because the intercept now thinks o2 is clean
```

The final line lazy loads orders and correctly retrieves o2 from the instance cache. However, it then calls `EntityBeanIntercept.setLoaded()` which resets changedProps and other things. This means that the change to o2.aValue does not get saved because the intercept no longer knows it is dirty.

I have confirmed that by changing EntityBeanIntercept to

```
public void setLoaded() {
    if (this.state == STATE_LOADED) {
      return;
    }

    this.state = STATE_LOADED;
    this.owner._ebean_setEmbeddedLoaded();
    this.lazyLoadProperty = -1;
    this.origValues = null;
    this.changedProps = null;
    this.dirty = false;
  }
```

that `o2.save()` works correctly. This is not the fix that you want to make, because it would break the "reset after insert/update" functionality you mention, but it highlights the issue.

**Comment by rbygrave** [comment] 2016-04-13 06:26
I can't get this to reproduce yet.

What is the version of Ebean you are using?
Is the code above accurate for the test case?  

findIterate().next() generally won't work without a hasNext() call.  In addition findIterate() has different semantics from findList() with a per object graph persistence context. So it's important to be accurate for this test case.

With those public fields I presume you are running in Play (you can't use field access outside Play etc).

Thanks, Rob.

**Comment by rbygrave** [comment] 2016-04-13 07:37
I've pushed up a test that does not reproduce the issue.

Can you post up a failing test case?

**Comment by rbygrave** [comment] 2016-04-17 21:29
Hi @jokester01au Are you able to post up a failing test?

**Comment by rbygrave** [comment] 2016-04-18 22:45
Hi @jokester01au, I'll close this issue given that I can't reproduce it. You can re-open it or add a comment etc with where you are at.

Thanks, Rob.

**Closed by rbygrave** 2016-04-18 22:45 UTC
Labels: Waiting for more information
