### ISSUE TITLE
Ebean RawSql Bug 

### ISSUE THREAD

**Issue by AdnanKukuljac** [ebean-orm/avaje-ebeanorm#250] opened 2015-02-20 11:09 UTC
Hi,

I am getting an error with this query:

Query (doesn't work):
```
RawSql rawSql = RawSqlBuilder.parse("SELECT id, name, date_created, date_updated FROM company order by :sortField :sort LIMIT :offset, :pageLimit").create();

```

Query (this query works):
```
RawSql rawSql = RawSqlBuilder.parse("SELECT id, name, date_created, date_updated FROM company LIMIT :offset, :pageLimit").create();
```

**Comment by rbygrave** [comment] 2015-02-25 03:21
*> RawSql rawSql = RawSqlBuilder.parse("SELECT id, name, date_created,
date_updated FROM company order by :sortField :sort LIMIT :offset,
:pageLimit").create();*

These 'named parameters' get converted into jdbc prepared statement bind
values so the sql becomes:

SELECT id, name, date_created, date_updated FROM company order by ? ? LIMIT
?, ?

When you say 'And my query doesn't work' ... I believe you are getting a
SQL error - the SQL is invalid right? ... because it is invalid to use a
bind variable for the order by clause?


In the second example the sql is converted to:

SELECT id, name, date_created, date_updated FROM company LIMIT ?, ?

... and this is valid, hence it works.


Does that make sense?

Cheers, Rob.

**Comment by rbygrave** [comment] 2015-03-18 19:59
I think I'll close this as not a bug with the view that the 'named parameters' are JDBC prepared statement bind parameters and as such are not valid to be used as :sortField and :sort above.

In those cases to be valid JDBC Ebean needs to know that some of the prepared statements are just string replacements rather than expected jdbc bind variables.  I don't think we want to introduce that complexity and those string replacements could instead occur prior to creating the RawSql instance.


Cheers, Rob.

**Closed by rbygrave** 2015-03-18 19:59 UTC
