### ISSUE TITLE
findPagingList() and findPagedList() broken on MS SQL Server

### ISSUE THREAD

**Issue by rbj325** [ebean-orm/avaje-ebeanorm#254] opened 2015-03-11 14:41 UTC
Hello,

I was testing out support for MS SQL Server through Ebean(v3.3.4 and v4.5.5) using the sqljdbc4.jar(Microsoft SQL Server JDBC Driver 4.1) and I was unable to get either paging method to produce the proper SQL.  In both cases the SQL generated was missing an alias on the SQL query which caused a PersistenceException.

I was not sure if this was an issue with the JDBC driver or something that EBean was doing under the hood, but was wondering if this has come up before?  I did not see any other issues in the bug queue.

**Comment by rbygrave** [comment] 2015-03-11 19:45
I'm sure this has not come up before  (so we can treat this as a new bug).

Can you post up the SQL and error?


Thanks, Rob.

**Comment by rbj325** [comment] 2015-03-11 20:08
Thanks for responding so quickly Rob.

The error is as follows:

[error] sbt.ForkMain$ForkError: java.util.concurrent.ExecutionException: javax.p
ersistence.PersistenceException: Query threw SQLException:Incorrect syntax near
')'.
[error] Bind values:[%product1%,%Product Desc1%,%drugcode1%]
[error] Query was:
[error] select count(*) from ( select distinct t0.id c0 from product t0 join dru
g_code u1 on u1.product_id = t0.id  where t0.identifier like ?  and t0.descripti
on like ?  and u1.identifier like ? )
[error]
[error]     at com.avaje.ebeaninternal.server.query.LimitOffsetPagingQuery.getTo
talRowCount(LimitOffsetPagingQuery.java:132)
[error]     at com.avaje.ebeaninternal.server.query.LimitOffsetPagingQuery.getTo
talPageCount(LimitOffsetPagingQuery.java:116)
[error]    at com.avaje.ebeaninternal.server.query.LimitOffsetPage.getTotalPage
Count(LimitOffsetPage.java:90)


The SQL that is being generated is:

select count(*) from ( select distinct t0.id c0 from product t0 
join drug_code u1 on u1.product_id = t0.id  
where t0.identifier like ?  and t0.description like ?  and u1.identifier like ? )


I was able to get that query to run properly in SSMS(Sql Server Management Studio) by adding an alias, "as a".  

So the working query would be:

select count(*) from ( select distinct t0.id c0 from product t0 
join drug_code u1 on u1.product_id = t0.id  
where t0.identifier like ?  and t0.description like ?  and u1.identifier like ? ) as a


I was working against Sql Server 2014 Express and Sql Server 2012.  I noticed that there were DbPlatform files in the source code for Sql Server 2000 and 2005.  Are there plans to add newer Sql Server support?

**Comment by rbygrave** [comment] 2015-03-11 20:30
*> Are there plans to add newer Sql Server support?*

Up until now DB Platform 2005 was suitable for all sql server after 2005.
With this we might need a new DBPlatform for 2012 and onwards yes.

**Comment by rbj325** [comment] 2015-03-11 20:59
Do you know a rough estimate on when this may be included in an official release?  I will try to dig into the source code further to see if I can help expedite the issue.

**Comment by rbygrave** [comment] 2015-03-11 21:05
The problem is probably
in com.avaje.ebean.config.dbplatform.MsSqlServer2005SqlLimiter

... I don't have easy access to MS SQL Server which is problematic (no
windows box handy).

**Comment by rbj325** [comment] 2015-03-12 02:52
Looking at that file you are appending the alias correctly so I'll see if I can create a test case to debug the issue.

**Comment by rbj325** [comment] 2015-03-12 03:01
Actually on second glance I believe there is an errant new line before the parenthesis where it should be after the parenthesis:

https://github.com/ebean-orm/avaje-ebeanorm/blob/master/src/main/java/com/avaje/ebean/config/dbplatform/MsSqlServer2005SqlLimiter.java#L59

**Comment by rbj325** [comment] 2015-03-26 13:27
Rob,

Do you have any plans to support/test MSSQL in the future?  It seems that fixing this bug may not be that big of an issue but if there is no plan to actively test against MSSQL during development the effort may be futile?

I noticed that the MSSQL connection was the only one commented out in the source code.

**Comment by rbygrave** [comment] 2015-03-26 20:17
Well I think 'futile' is a bit harsh.  It is pretty easy to run all the
tests against a given DB, you just need to have that database setup and
available.

MS SQL Server for me has the issue of needing a windows box or using
Azure.  I have used Azure but that costs money so I won't have that sitting
around until support contracts offset that cost.  Continuous testing
against MS SQL Server could follow that.

I'm not sure that answers your question.  MS SQL Server has potential to be
a good database for a lot of people and makes some 'commercial' sense for
some people. I wish they would sort out support of jdbc batch insert
returning generated keys (which I think is a massive blunder).  I
personally have not had to use it in anger since SQL Server 2000 but I am
aware of the architectural improvements they have made since then.

Someone who actively uses MS SQL Server may choose to help the project by
actively running the tests against newer database versions as they come
out.  Perhaps you might even be the person to do that - right not I can't
commit to that though.

Anyway, hopefully that answers your question.


Cheers, Rob.

**Comment by Ryszard-Trojnacki** [comment] 2015-03-27 07:22
I have configured hudson for my project with databases:
- Debian with MySQL
- Debian with PostgreSQL 9.3
- Debian with PostgreSQL 9.4
- Microsoft Windows 2012 with Microsoft SQL Server 2008
- Microsoft Windows 2012 with Microsoft SQL Server 2012
and I will add SQL Server 2014 in near future.

I will add Ebean with GIT pull to my hudson configuration to test newest versions.

**Comment by Ryszard-Trojnacki** [comment] 2015-03-27 07:23
I have configured hudson for my project with databases:
- Debian with MySQL
- Debian with PostgreSQL 9.3
- Debian with PostgreSQL 9.4
- Microsoft Windows 2012 with Microsoft SQL Server 2008
- Microsoft Windows 2012 with Microsoft SQL Server 2012
and I will add SQL Server 2014 in near future.

I will add Ebean with GIT pull to my hudson configuration to test newest versions.

**Comment by rbj325** [comment] 2015-03-27 13:07
Thank you for your quick responses.  

@rbygrave Yes, that did answer my question and I am planning on helping with this bug.

@Ryszard-Trojnacki Thank you for taking the time to set that up.  I'm interested to hear if the tests pass for 2008 as I only tested 2012/2014, but also I need to confirm that there is a test in place that covers this feature or at least reproduces this bug.

**Comment by rbj325** [comment] 2015-04-03 18:07
So I was trying to execute the paging test I had setup against MS SQL in the Ebean source code and I was receiving this error:

Connected to the target VM, address: '127.0.0.1:51450', transport: 'socket'
14:00:07.833 [main] INFO  c.a.e.server.lib.sql.DataSourcePool - DataSourcePool [ms] autoCommit[false] transIsolation[READ_COMMITTED] min[2] max[20]
14:00:40.866 [main] ERROR c.a.e.s.deploy.BeanDescriptorManager - Error in deployment
java.lang.IllegalStateException: Bean class com.avaje.tests.compositekeys.db.AuditInfo is not enhanced?
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.setEntityBeanClass(BeanDescriptorManager.java:1365) ~[classes/:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.createByteCode(BeanDescriptorManager.java:1103) ~[classes/:na]


If you can point me in the right direction for configuring this test I should be able to debug the issue.

I have my sql connection info in the ebean.properties file and I added the sqljdbc4.jar dependency setup.  I'm just not sure why it's picking up the AuditInfo class and complaining about it.  

I pulled the latest from master this morning so not sure if that's in flux or not.

**Comment by rbygrave** [comment] 2015-05-07 21:18
Sorry, I dropped the ball on this one.  Where are you at with this issue?

**Comment by rbj325** [comment] 2015-05-10 17:10
I haven't had a chance to come back to it yet but I'm assuming it's just a configuration issue when I'm trying to run the test suite.

**Comment by rbygrave** [comment] 2015-06-24 11:45
I'll just close this issue for now.  We can reopen it if needed.

**Closed by rbygrave** 2015-06-24 11:45 UTC
Labels: bug

**Comment by maichler** [comment] 2015-11-13 20:44
I ran into the same problem today using SQLServer 2008 R2. While debugging I came across the following code block from `CQueryBuilder#buildRowCountQuery()`:

```java
    if (hasMany) {
        sql = "select count(*) from ( " + sql + ")";
        if (selectCountWithAlias) {
            sql += " as c";
        }
    }
```
The field `selectCountWithAlias` holds the value retrieved from  `DatabasePlatform#isSelectCountWithAlias()`. 

Creating a custom database platform which extends `MsSqlServer2005Platform` where this flag is set to `true` solved this problem for me.

```java
    public class CustomMSSqlServerPlatform extends MsSqlServer2005Platform {
        public CustomMSSqlServerPlatform() {
            super();
            this.selectCountWithAlias = true;
        }
    }
````

**Comment by rbj325** [comment] 2015-11-13 23:26
@maichler That sounds like what I was looking to find with debugging but never got the chance.  Thank you for following up.
