### ISSUE TITLE
Context.toList error for Jackson module

### ISSUE THREAD

**Issue by icode** [ebean-orm/avaje-ebeanorm#295] opened 2015-05-14 06:33 UTC
com.avaje.ebeaninternal.server.deploy.BeanDescriptorJsonHelp
`event != JsonToken.START_ARRAY` is error

```
public <T> List<T> toList(Class<T> cls, JsonParser src) throws JsonIOException {
        try {
            BeanDescriptor e = this.getDescriptor(cls);
            ArrayList list = new ArrayList();
            JsonToken event = src.nextToken();
            // this is a START_OBJECT
            if(event != JsonToken.START_ARRAY) {
                throw new JsonParseException("Expecting start_array event but got " + event, src.getCurrentLocation());
            } else {
                while(true) {
                    Object bean = e.jsonRead(src, (String)null);
                    if(bean == null) {
                        return list;
                    }

                    list.add(bean);
                }
            }
        } catch (IOException var7) {
            throw new JsonIOException(var7);
        }
    }
```

**Comment by icode** [comment] 2015-05-16 15:12
Please check this issue, thi's block. thanks

**Comment by icode** [comment] 2015-07-09 05:18
@rbygrave Please check this issue, thi's block. thanks! Now ebean has not read `List` it's read list item.

**Comment by rbygrave** [comment] 2015-07-19 20:52
Have you got a test case for this?

**Comment by icode** [comment] 2015-07-20 10:38
Please change `org.avaje.ebeanorm.jackson.FindDeserializers.findCollectionDeserializer` to

```
        Class clazz = type.getContentType().getRawClass();
       if (Collection.class.isAssignableFrom(type.getRawClass())
                && jsonContext.isSupportedType(clazz)) {
            return new BeanListTypeDeserializer(jsonContext, clazz);
        }
```

Old code `type.getRawClass().isAssignableFrom(BeanCollection.class)` has issue, because interface always `java.util.List`

**Comment by rbygrave** [comment] 2015-07-24 08:36
So this problem is on the avaje-ebeanorm-jackson and not on the avaje-ebeanorm project ?

I'll have a look over there.

**Comment by icode** [comment] 2015-07-24 08:38
@rbygrave No, this problem is all, but difference issue.

**Comment by rbygrave** [comment] 2015-07-24 08:41
Ok.  Different issue means you should create a different issue  ... specifically the commits get linked back to the issue.  So it is A) confusing and B) can't link the commits to the issues correctly.

**Comment by rbygrave** [comment] 2015-07-24 08:42
So for this issue ... do you have a test case? Some code that shows the scenario that causes some problem.

**Comment by icode** [comment] 2015-07-24 08:44
Because `avaje-ebeanorm-jackson` not support multi ebean server, so i fork it and change.

I try to write a test case, please wait.

**Comment by rbygrave** [comment] 2015-07-24 08:45
> has issue, because interface always java.util.List
No, it looks correct. Specifically is not expected to process java.util.List but only the specific Ebean BeanCollection.  So no I don't think your change is correct.  Create a test case to show your problem.

**Comment by icode** [comment] 2015-07-24 08:48
Em, this is `avaje-ebeanorm-jackson` issue. And I change it, can support mutil server.

like this:

```
JacksonEbeanModule module = new JacksonEbeanModule(server, locator);
objectMapper.registerModules(module);
```

**Comment by icode** [comment] 2015-07-24 08:53
@rbygrave this is a model, `models` property should be Ebean `BeanCollection`, because MyEbeanModel is ebean entity.

```
public static class Project {
    List<MyEbeanModel> models;
}
```

**Comment by icode** [comment] 2015-07-24 09:51
This test case can reshow issuse.

```
import ameba.db.ebean.jackson.BeanListTypeDeserializer;
import ameba.db.ebean.jackson.BeanTypeDeserializer;
import com.avaje.ebean.EbeanServer;
import com.avaje.ebean.EbeanServerFactory;
import com.avaje.ebean.config.DataSourceConfig;
import com.avaje.ebean.config.ServerConfig;
import com.avaje.ebean.text.json.JsonContext;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.deser.Deserializers;
import com.fasterxml.jackson.databind.jsontype.TypeDeserializer;
import com.fasterxml.jackson.databind.jsontype.TypeSerializer;
import com.fasterxml.jackson.databind.module.SimpleModule;
import com.fasterxml.jackson.databind.ser.Serializers;
import com.fasterxml.jackson.databind.type.CollectionType;
import com.google.common.collect.Lists;
import org.avaje.agentloader.AgentLoader;
import org.h2.Driver;
import org.junit.Test;

import javax.persistence.Entity;
import java.io.IOException;
import java.lang.instrument.IllegalClassFormatException;
import java.util.Collection;
import java.util.List;

/**
 * @author icode
 */
public class EbeanTest {

    @Test
    public void JsonTest() throws IOException, IllegalClassFormatException, ClassNotFoundException {
        AgentLoader.loadAgentFromClasspath("avaje-ebeanorm-agent", "debug=5");
        ObjectMapper mapper = new ObjectMapper();
        final ServerConfig config = new ServerConfig();
        config.setClasses(Lists.<Class<?>>newArrayList(Item.class));
        DataSourceConfig dataSourceConfig = new DataSourceConfig();
        dataSourceConfig.setUrl("jdbc:h2:file:./db");
        dataSourceConfig.setDriver(Driver.class.getName());
        dataSourceConfig.setUsername("sa");
        dataSourceConfig.setPassword("");
        config.setDataSourceConfig(dataSourceConfig);
        config.setName("default");
        EbeanServer server = EbeanServerFactory.create(config);
        mapper.registerModules(new JacksonEbeanModule(server));
        Project project = mapper.readValue("{\"items\":[{\"name\":\"item0\"}]}", Project.class);
        System.out.println("------------------------");
        System.out.println(project);
    }

    public static class Project {

        private List<Item> items;

        public List<Item> getItems() {
            return items;
        }

        public void setItems(List<Item> items) {
            this.items = items;
        }
    }

    @Entity
    public static class Item {

        private String name;

        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }
    }

    public class JacksonEbeanModule extends SimpleModule {

        private final JsonContext jsonContext;
        private final EbeanServer server;

        /**
         * Construct with a JsonContext obtained from an EbeanServer.
         */
        public JacksonEbeanModule(EbeanServer server) {
            this.server = server;
            this.jsonContext = server.json();
        }

        @Override
        public String getModuleName() {
            return "jackson-datatype-ebean-server-" + server.getName();
        }

        /**
         * Register the Ebean specific serialisers and deserialisers.
         */
        @Override
        public void setupModule(SetupContext context) {
            FindSerializers serializers = new FindSerializers(jsonContext);
            context.addSerializers(serializers);

            FindDeserializers deserializers = new FindDeserializers(jsonContext);
            context.addDeserializers(deserializers);
        }

    }

    class FindSerializers extends Serializers.Base {
        private final JsonContext jsonContext;

        FindSerializers(JsonContext jsonContext) {
            this.jsonContext = jsonContext;
        }

        @Override
        public JsonSerializer<?> findSerializer(SerializationConfig config, JavaType type, BeanDescription beanDesc) {

            if (jsonContext.isSupportedType(type.getRawClass())) {
                return createSerializer();
            }

            return null;
        }

        @Override
        public JsonSerializer<?> findCollectionSerializer(SerializationConfig config, CollectionType type, BeanDescription
                beanDesc, TypeSerializer elementTypeSerializer, JsonSerializer<Object> elementValueSerializer) {

            if (Collection.class.isAssignableFrom(type.getRawClass())
                    && jsonContext.isSupportedType(type.getContentType().getRawClass())) {
                return createSerializer();
            }

            return null;
        }

        private JsonSerializer createSerializer() {
            return new CommonBeanSerializer(jsonContext);
        }

    }

    public class CommonBeanSerializer<T> extends JsonSerializer<T> {

        private final JsonContext jsonContext;

        /**
         * Construct with the given JsonContext.
         */
        CommonBeanSerializer(JsonContext jsonContext) {
            this.jsonContext = jsonContext;
        }

        /**
         * Serialize entity beans or collections.
         */
        @Override
        public void serialize(T o, JsonGenerator jsonGenerator, SerializerProvider serializerProvider) throws IOException {
            jsonContext.toJson(o, jsonGenerator);
        }
    }

    class FindDeserializers extends Deserializers.Base {

        private final JsonContext jsonContext;

        /**
         * Construct with the given JsonContext.
         */
        FindDeserializers(JsonContext jsonContext) {
            this.jsonContext = jsonContext;
        }

        @Override
        public JsonDeserializer<?> findBeanDeserializer(JavaType type,
                                                        DeserializationConfig config,
                                                        BeanDescription beanDesc) throws JsonMappingException {

            if (jsonContext.isSupportedType(type.getRawClass())) {
                return new BeanTypeDeserializer(jsonContext, type.getRawClass());
            }
            return null;
        }

        @Override
        public JsonDeserializer<?> findCollectionDeserializer(CollectionType type,
                                                              DeserializationConfig config,
                                                              BeanDescription beanDesc,
                                                              TypeDeserializer elementTypeDeserializer,
                                                              JsonDeserializer<?> elementDeserializer)
                throws JsonMappingException {
            // todo this is a ebean bug
            Class clazz = type.getContentType().getRawClass();
            if (Collection.class.isAssignableFrom(type.getRawClass())
                    && jsonContext.isSupportedType(clazz)) {
                return new BeanListTypeDeserializer(jsonContext, clazz);
            }
            return null;
        }


    }

}
```

**Comment by rbygrave** [comment] 2015-11-05 03:47
Yes, reproduced as per https://github.com/ebean-orm/avaje-ebeanorm-jackson/issues/5
Also refer to https://github.com/ebean-orm/avaje-ebeanorm/issues/451

**Comment by rbygrave** [comment] 2015-11-05 03:58
Fixed / duplicate of #451

**Closed by rbygrave** 2015-11-05 03:58 UTC
Labels: bug

**Comment by icode** [comment] 2015-11-05 05:03
When release 6.10.4 to maven ? @rbygrave

**Comment by rbygrave** [comment] 2015-11-05 05:55
Probably a day or two.  I need to review what else can go in that release.
