### ISSUE TITLE
sqlQuery support sql page limit on all Database platform

### ISSUE THREAD

**Issue by icode** [ebean-orm/avaje-ebeanorm#279] opened 2015-04-23 05:56 UTC
how to use SqlQuery for sql page limit on all Database platform

**Comment by rbygrave** [comment] 2015-04-24 09:52
I think this is effectively a duplicate of #278.  That is, SqlQuery currently does not modify the SQL (using LIMIT/OFFSET or similar) to support paging.

So the answer is, it currently does not support paging.

However, via #278 we should add support for paging to SqlQuery by modifying the SQL as necessary (with LIMIT OFFSET etc).

**Comment by rbygrave** [comment] 2015-04-24 11:20
Closing this issue - refer to #278 for a fix.

**Closed by rbygrave** 2015-04-24 11:20 UTC
Labels: question
