### ISSUE TITLE
pom version numbering - not including x.y.0 versions like 6.14.0 

### ISSUE THREAD

**Issue by flqw** [ebean-orm/avaje-ebeanorm#521] opened 2016-01-07 10:24 UTC
In my opinion the current version numbering is rather confusing, since there are missing releases (e.g. 6.13.5 -> 6.14.1, missing 6.14.0). Considering http://semver.org/, the PATCH version must reset to zero if the MINOR is increased, and MINOR and PATCH must be reset to zero, if the MAJOR is increased.

What do you think?

**Comment by rbygrave** [comment] 2016-01-07 10:34
I never use 0 in pom version ... and the reason is because when you want to use maven version ranges the x.y.0-SNAPHOT gets included when you don't want it to.

That is for example ...    [2,3) ... includes 3.0-SNAPSHOT which I'd describe as unhelpful.

So yes, I intentionally just have the global rule that I don't use 0 in my maven pom versions.  Yes I know about semver.org and I've been involved in a few of these debates as to how maven works and specifically the maven version ranges and x.y.0-SNAPSHOT.

So I'm happy that 6.14.1 is in fact the first version in the 6.14 range because in general maven version ranges are important to me.

**Comment by rbygrave** [comment] 2016-01-07 11:11
Just to extend that a bit.  I've be using maven version ranges for the past 8 years I think now and version ranges have proven to be a very important technique when modularizing large applications (breaking large applications into smaller modules and driving re-use across an organisation).  

So both semantic versioning and maven version ranges are very important to me (because you can't use version ranges in a meaningful way without semantic versioning).  Once you get into the issues with x.y.0-SNAPSHOT ... it becomes a pretty good nice simple rule just to forgo that x.y.0-SNAPSHOT and always start with x.y.1-SNAPSHOT.

So yes, never using the 0 is not a whim for me but instead a simple practical rule with a lot of success behind it. I suggest you'll have to do well to change my mind here.

On the other hand ... I SERIOUSLY suggest you strongly consider dropping those 0-SNAPSHOTs yourself (assuming you are into maven version ranges and modularization of large applications).

Cheers, Rob.

Sorry if that comes across a bit strong but honestly my use and view of maven was significantly changed when I was shown how to use version ranges and semantic versioning to modularise apps (with Spring mostly) and dropping those 0-SNAPSHOTS is in my top 5 maven tips for sure.

**Comment by flqw** [comment] 2016-01-07 11:30
I also use maven and semver across multiple projects and never came across the problem that maven included a 3.0 snapshot for a [2,3) range. I even had to explicitly add 3.0.SNAPSHOT to my range to force maven to do so. Are you sure that is the case?

Seems weird to me, especially considering that no other project that i know of uses that approach.

**Comment by rbygrave** [comment] 2016-01-07 11:42
Yes I'm sure.  Have a read of https://issues.apache.org/jira/browse/MNG-3092 ... if you haven't already, yes it's a long discussion there.

Some comments in there are from the guys who I directly learnt my best maven skills/tricks from (Richard Volwes and Michael McCallum).

**Comment by rbygrave** [comment] 2016-01-07 11:44
The last time I confirmed this issue still exists was about 6 months ago .. to re-affirm the rule - never use a version ending in 0 (or just simplify it to never use zeros at all).

**Comment by rbygrave** [comment] 2016-01-07 22:53
I'll close this now.  Re-open if you would like to discuss more or push the issue more etc.

**Closed by rbygrave** 2016-01-07 22:53 UTC
Labels: question

**Comment by rbygrave** [comment] 2016-01-07 23:07
For posterity (people reading this ticket in the future):

Lets say I have 6.16.0-SNAPSHOT installed.

    <dependency>
      <groupId>org.avaje.ebeanorm</groupId>
      <artifactId>avaje-ebeanorm</artifactId>
      <version>[6.14,6.15.99999)</version>
    </dependency>

mvn dependency:tree

[INFO] org.junk:a-basic-example:jar:1.0.1-SNAPSHOT
[INFO] +- org.avaje.ebeanorm:avaje-ebeanorm:jar:6.15.1:compile
...


... so that is as we expect (that 6.16.0-SNAPSHOT is not included in the range) because of the 6.15.9999 but ...

    <dependency>
      <groupId>org.avaje.ebeanorm</groupId>
      <artifactId>avaje-ebeanorm</artifactId>
      <version>[6.14,6.16)</version>
    </dependency>

mvn dependency:tree

[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ a-basic-example ---
[INFO] org.junk:a-basic-example:jar:1.0.1-SNAPSHOT
[INFO] +- org.avaje.ebeanorm:avaje-ebeanorm:jar:6.16.0-SNAPSHOT:compile
...
so [6.14,6.16) ... actually includes 6.16.0-SNAPSHOT and that is what people generally do not expect and this is the issue we want to avoid and hence the "never use 0-SNAPSHOT" rule.

**Comment by rbygrave** [comment] 2016-01-10 22:41
Comments from Mark Derricutt:

*Your comments all sound...sound. On a slight aside, you'll ONLY resolve the .0-SNAPSHOT if it's installed locally, since by default Maven won't resolve snapshots (unless you've also declared a snapshots repository).* 

*The same can be said for non snapshots as well, if you're using a -alpha -beta -cr and finally a -ga suffix the range will still resolve to something you don't necessarily want, or expect.* 

So 2 good points from Mark.
1. You tend to avoid this issue on build servers when on snapshots are included (but hit it locally)
2. You can also hit this issue with the -alpha, -beta, -cr style suffixes (e.g. a 3.0-CR version can similarly resolve in a [2,3) range.


Comments from Michael McCallum
*Statements are accurate. Personally I only use 2 point versions as the extra point makes for ambiguity, IMO you broke it or you didn't.* 

A good point from Michael - often easiest to just have 2 point versions.
