### ISSUE TITLE
springboot devtools and ebean build error

### ISSUE THREAD

**Issue by vodcms** [ebean-orm/avaje-ebeanorm#446] opened 2015-10-29 03:11 UTC
Caused by: java.lang.ClassCastException: xxx.xxx.app.steam.models.SteamItem cannot be cast to xxx.xxx.app.steam.models.SteamItem.

but i remove spring-boot-devtools  build is ok.

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.test</groupId>
	<artifactId>test</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>jar</packaging>

	<name>test</name>
	<description>test web rest api services</description>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.3.0.M5</version>
		<relativePath /> <!-- lookup parent from repository -->
	</parent>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<java.version>1.8</java.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-cache</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-mongodb</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-solr</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-tomcat</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-jetty</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-websocket</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-redis</artifactId>
			</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security</artifactId>
		</dependency>

		<dependency>
			<groupId>mysql</groupId>
			<artifactId>mysql-connector-java</artifactId>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.avaje.ebeanorm</groupId>
			<artifactId>avaje-ebeanorm-agent</artifactId>
			<version>4.7.1</version>
		</dependency>
		<dependency>
			<groupId>org.avaje</groupId>
			<artifactId>avaje-agentloader</artifactId>
			<version>2.1.2</version>
		</dependency>
		<dependency>
			<groupId>org.jsoup</groupId>
			<artifactId>jsoup</artifactId>
			<version>1.8.3</version>
		</dependency>
		<dependency>
			<groupId>org.avaje.ebeanorm</groupId>
			<artifactId>avaje-ebeanorm-spring</artifactId>
			<version>4.5.3</version>
		</dependency>
		<dependency>
			<groupId>com.google.code.gson</groupId>
			<artifactId>gson</artifactId>
		</dependency>
		<dependency>
			<groupId>org.avaje.ebeanorm</groupId>
			<artifactId>avaje-ebeanorm</artifactId>
			<version>6.10.1</version>
		</dependency>
<dependency>
    <groupId>com.google.guava</groupId>
    <artifactId>guava</artifactId>
    <version>18.0</version>
</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

	<repositories>
		<repository>
			<id>spring-snapshots</id>
			<name>Spring Snapshots</name>
			<url>https://repo.spring.io/snapshot</url>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</repository>
		<repository>
			<id>spring-milestones</id>
			<name>Spring Milestones</name>
			<url>https://repo.spring.io/milestone</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</repository>
	</repositories>
	<pluginRepositories>
		<pluginRepository>
			<id>spring-snapshots</id>
			<name>Spring Snapshots</name>
			<url>https://repo.spring.io/snapshot</url>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</pluginRepository>
		<pluginRepository>
			<id>spring-milestones</id>
			<name>Spring Milestones</name>
			<url>https://repo.spring.io/milestone</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</pluginRepository>
	</pluginRepositories>

</project>

```

**Comment by rbygrave** [comment] 2015-10-29 03:47
What is the stack trace?

**Comment by rbygrave** [comment] 2015-10-29 03:53
I was not able to reproduce by modifying the project https://github.com/ebean-orm/example-springboot

It would be good if you can reproduce by forking that project.

**Comment by wilkinsona** [comment] 2015-10-29 09:35
This may well be a variant of one of these existing Spring Boot issues:

 - https://github.com/spring-projects/spring-boot/issues/3697
 - https://github.com/spring-projects/spring-boot/issues/3316

**Comment by vodcms** [comment] 2015-10-30 02:49
TKS ALL。 I ignore it

**Comment by rbygrave** [comment] 2015-10-30 08:41
I'll close this then.

**Closed by rbygrave** 2015-10-30 08:41 UTC

**Comment by netwolfuk** [comment] 2016-06-24 10:01
As of spring-boot 1.3.0, one can now tell spring-boot to include the ebean jar(s) in the `RestartClassLoader`. 

Create the properties file `src/main/resources/META-INF/spring-devtools.properties` containing:
```
restart.include.ebean=/avaje-ebean.*\.jar
```
From my limited testing this appears to resolve the problem for me. I am not using the ebean-generator jars in Eclipse but if one is using those, the contents of that file may need to contain more regex lines.
