### ISSUE TITLE
How can I map tables has same primary id

### ISSUE THREAD

**Issue by caoli5288** [ebean-orm/avaje-ebeanorm#478] opened 2015-12-04 14:04 UTC
A project, it left some of the tables. These tables are associated with same primary key. 
Now I take over this project, I want to map data through ebean. How can I do?

**Comment by rbygrave** [comment] 2015-12-04 21:04
I don't understand yet. Can you explain more fully ? Perhaps include a
description of the tables in question?

Thanks, Rob.

**Comment by wenzhihong2003** [comment] 2015-12-05 00:34
I think @caoli5288 mean in OneToOne relation, the two table share key. like this blog descript
http://websystique.com/hibernate/hibernate-one-to-one-unidirectional-with-shared-primary-key-annotation-example/

**Comment by wenzhihong2003** [comment] 2015-12-05 00:35
It's a very useful future for me too

**Comment by caoli5288** [comment] 2015-12-05 12:21
@wenzhihong2003 Yes. I mean it.

**Comment by caoli5288** [comment] 2015-12-07 02:40
@rbygrave The `@PrimaryKeyJoinColumn` Probably not working. I create entity class like @wenzhihong2003 says.

**Comment by rbygrave** [comment] 2015-12-07 03:14
> I create entity class like ...

You have not provided sufficient information. You need to provide YOUR tables, primary keys, foreign keys and YOUR entity beans.

**Comment by rbygrave** [comment] 2015-12-07 03:16
This could be a duplicate of #107 but there is not sufficient information to say that yet.

**Comment by caoli5288** [comment] 2015-12-07 03:25
```sql
CREATE TABLE `user` (
`id`  int(11) NOT NULL AUTO_INCREMENT ,
`name`  varchar(16) NOT NULL ,
PRIMARY KEY (`id`)
);
```
```sql
CREATE TABLE `user_attribute` (
`id`  int(11) NOT NULL AUTO_INCREMENT ,
`strength`  int(11) NULL ,
`agility`  int(11) NULL ,
`physique`  int(11) NULL ,
`resistance`  int(11) NULL ,
PRIMARY KEY (`id`)
);
```
```java
@Entity
public class User {

    @Id
    private int id;

    @Column
    private String name;

    @OneToOne
    @PrimaryKeyJoinColumn
    private UserAttribute attribute;

    // getter and setter here
}
```
@rbygrave

**Comment by rbygrave** [comment] 2015-12-07 06:55
> Yes. It can be resolve by @JoinColumn.

This statement is not clear.  There is no @JoinColumn in your model so I don't know what you are trying to say here. 

In regards the SQL and beans - You don't have a FK between the 2 primary keys but I assume that is simply an omission (you forgot to include the foreign key DDL statement). Assuming that is the case this is a duplicate of #107 especially as you include @PrimaryKeyJoinColumn which as per #107 is an enhancement request.

**Comment by rbygrave** [comment] 2015-12-08 21:29
I'll close this as a duplicate of #107.  Reopen if required.

**Closed by rbygrave** 2015-12-08 21:29 UTC
Labels: question
