### ISSUE TITLE
@OneToMany in @MappedSuperclass throws NullpointerException

### ISSUE THREAD

**Issue by maherm** [ebean-orm/avaje-ebeanorm#437] opened 2015-10-19 07:01 UTC
When there is an *unidirectional* @OneToMany relation on a @MappedSuperclass entity, I get a NPE while creating the server: 

    java.lang.NullPointerException
	at com.avaje.ebeaninternal.server.deploy.meta.DeployBeanPropertyAssoc.setBeanTable(DeployBeanPropertyAssoc.java:99)
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.makeUnidirectional(BeanDescriptorManager.java:837)
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.checkMappedByOneToMany(BeanDescriptorManager.java:905)
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.checkMappedBy(BeanDescriptorManager.java:701)
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.readEntityRelationships(BeanDescriptorManager.java:616)
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.deploy(BeanDescriptorManager.java:286)
	at com.avaje.ebeaninternal.server.core.InternalConfiguration.<init>(InternalConfiguration.java:129)
	at com.avaje.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:124)
	at com.avaje.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:41)
	at com.avaje.ebean.EbeanServerFactory.createInternal(EbeanServerFactory.java:108)
	at com.avaje.ebean.EbeanServerFactory.create(EbeanServerFactory.java:67)
	at EbeanNullpointerTest.test(EbeanNullpointerTest.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by rbygrave** [comment] 2015-10-22 00:46
>  unidirectional @OneToMany relation on a @MappedSuperclass entity,

Do you only have 1 class extending the @MappedSuperclass? If so why not just move the mapping up to that.  If you have multiple classes extending the @MappedSuperclass then the mapping makes less sense (as you need a FK per class type) - you'll need to explain/show more of your mapping in that case.

**Comment by maherm** [comment] 2015-10-22 07:26
I have multiple classes extending the MappedSuperclass. I broke it down to a minimal example to reproduce the exception:

```java
@MappedSuperclass
public class ParentClass {
    @Id private String id;

    @OneToMany(cascade=CascadeType.ALL)
    private List<Item> items;

    //Getters and setters
    ....
}
```
```java
@Entity
public class Item {
    @Id private String name;
    
    //Getters and setters
    ....
}
```
```java
@Entity
public class ConcreteEntity extends ParentClass{
}
```

I create the server with:
```java
@Test
public void test(){ 
    ServerConfig config = new ServerConfig();
    config.setName("h2");
    config.setDefaultServer(true);
    config.loadFromProperties();
    EbeanServerFactory.create(config); 
}
```
Why wouldn't that make sense? The documentation for @MappedSuperclass says:

>The MappedSuperclass annotation designates a class whose mapping information is applied to the
entities that inherit from it. A mapped superclass has no separate table defined for it.
A class designated with the MappedSuperclass annotation can be mapped in the same way as an
entity except that the mappings will apply only to its subclasses since no table exists for the mapped
superclass itself. When applied to the subclasses the inherited mappings will apply in the context of the subclass tables.

I don't see why that should not apply to OneToMany

**Comment by rbygrave** [comment] 2015-10-22 08:49
What do the associated db tables look like?  Specifically interested in the
foreign key columns.

**Comment by maherm** [comment] 2015-10-22 09:20
I genereate them using the *.properties file from the Quick Start Guide. Only difference is I'm using a regular file based database instead of the in-memory db.

```ini
# generate DDL files
ebean.ddl.generate=true
# run ddl drops and recreates tables
ebean.ddl.run=true

ebean.uuidStoreAsBinary=true
ebean.databaseSequenceBatchSize=1

ebean.debug.sql=true
ebean.debug.lazyload=false

datasource.default=h2
datasource.h2.username=sa
datasource.h2.password=
datasource.h2.databaseUrl=jdbc:h2:./db/eb;AUTO_SERVER=true
datasource.h2.databaseDriver=org.h2.Driver
```
But it looks like the exception is thrown before (or while?) the tables are generated, because there is no *.sql file in my working directory and if I open the database afterwards using the h2 client there are no tables.

**Comment by rbygrave** [comment] 2015-10-29 04:58
If you move List<Item> items; ... up to each of your classes that extend ParentClass and generated the DDL ... then the resulting item table would have a foreign key back to each of those types.

To me the resulting DB design 'will look odd' / 'fishy'.  It seems a bit strange from an ORM perspective in that they will also be unidirectional - will not have the @ManyToOne side of the relationship. Unidirectional relationships typically imply ownership - the  ConcreteEntity 'owns' its related Item instances ... the items can't be created without the ConcreteEntity etc.

**Comment by rbygrave** [comment] 2015-10-30 09:03
> Why wouldn't that make sense? The documentation for @MappedSuperclass says: ...

The issue is that a @OneToMany implies a foreign key. @MappedSuperclass implies multiple concrete @Entity (so multiple tables to relate the foreign key back to = multiple foreign keys).  The normal bi-directional @OneToMany has a mappedBy attribute but that can not map back to the @MappedSuperclass (which instance?) ... so what is implied is multiple unidirectional relationships (to the save entity/table) and that does not make sense.

I think you'll see that when you move the @OneToMany up from the @MappedSuperclass to each @Entity.

I'll close this for now.  Reopen if you wish to take it further.

**Closed by rbygrave** 2015-10-30 09:03 UTC
