### ISSUE TITLE
'Matches for the concatinated key columns where not found'

### ISSUE THREAD

**Issue by ksperling** [ebean-orm/avaje-ebeanorm#614] opened 2016-03-22 10:53 UTC
I'm trying to model the bridge entity of a many-to-many relationship directly so that I can define additional properties on it, however I get the exception mentioned above.

Looking into the Ebean code for `BindableIdEmbedded` / `MatchedImportedProperty` it seems that the properties have no way of matching up due to [`BeanPropertyAssocOne.importedPrimaryKey`](https://github.com/ebean-orm/avaje-ebeanorm/blob/master/src/main/java/com/avaje/ebeaninternal/server/deploy/BeanPropertyAssocOne.java#L73) being set to false unconditionally.

Is this a bug or am I just doing it wrong? For reference, the entity class is below.

```
@Entity @NoArgsConstructor
public class SiteUser {

  @Embeddable @EqualsAndHashCode
  public static class Id {
    private UUID site;
    private UUID user;
  }

  @EmbeddedId
  private Id id;

  @ManyToOne(optional=false) @Getter
  private Site site;

  @ManyToOne(optional=false) @Getter
  private User user;

  // other properties...
}
```

**Comment by rbygrave** [comment] 2016-03-22 19:31
Hi Karsten,

This looks about right (suggesting a bug) with a question mark over the issue that the mapping likely leads to duplicate "site" and "user" columns.

So normally I'd expect to see additional @JoinColumn annotations like:

```java

  @ManyToOne(optional=false) @Getter
  @JoinColumn(name = "site", nullable = false, insertable = false, updatable = false)
  private Site site;

  @ManyToOne(optional=false) @Getter
  @JoinColumn(name = "user", nullable = false, insertable = false, updatable = false)
  private User user;

```

That does not sound like it causes the issue though.  

Do you have a full stack trace? can you include that if you have it?

Thanks, Rob.

**Comment by ksperling** [comment] 2016-03-22 19:47
Hi Rob, thanks for the quick response. I've added the `@JoinColumn` annotations, the stack trace stays the same though:
```
javax.persistence.PersistenceException: Matches for the concatinated key columns where not found? I expect that the concatinated key was null, and this bean does not have ManyToOne assoc beans matching the primary key columns?
	at com.avaje.ebeaninternal.server.persist.dmlbind.BindableIdEmbedded.deriveConcatenatedId(BindableIdEmbedded.java:88)
	at com.avaje.ebeaninternal.server.persist.dml.InsertMeta.deriveConcatenatedId(InsertMeta.java:142)
	at com.avaje.ebeaninternal.server.persist.dml.InsertHandler.bind(InsertHandler.java:79)
	at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:69)
	at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.insert(DmlBeanPersister.java:50)
	at com.avaje.ebeaninternal.server.persist.DefaultPersistExecute.executeInsertBean(DefaultPersistExecute.java:54)
	at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeNow(PersistRequestBean.java:608)
	at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeOrQueue(PersistRequestBean.java:654)
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.insert(DefaultPersister.java:449)
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveRecurse(DefaultPersister.java:424)
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveAssocManyDetails(DefaultPersister.java:1047)
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveMany(DefaultPersister.java:937)
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveAssocMany(DefaultPersister.java:813)
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.insert(DefaultPersister.java:453)
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.insert(DefaultPersister.java:399)
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.save(DefaultPersister.java:387)
	at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1485)
	at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1478)
	at sample.Domain.save(Domain.java:49)
        ...
```

Let me know if there's anything else I can do to help debug this.

**Comment by rbygrave** [comment] 2016-03-22 20:08
I'm expecting the insert code looks like:

```java
SiteUser siteUser = new SiteUser();
siteUser.setUser(...);
siteUser.setSite(...);
server.save(siteUser);
```

I'll look to reproduce it.

**Comment by ksperling** [comment] 2016-03-22 20:36
Yeah pretty much -- I've actually got that bit in a SiteUser constructor that I forgot to include above (but there's a no-arg constructor as well).

```
  public SiteUser(Site site, User user, AccessLevel access) {
    this.site = Arguments.requireNonNull(site);
    this.user = Arguments.requireNonNull(user);
    this.access = Arguments.requireNonNull(access);
    site.getUsers().add(this);
    user.getSites().add(this);
  }
```

**Comment by rbygrave** [comment] 2016-03-23 04:07
Right so yes this was a bug and now fixed in master.

Your mapping should work exactly as you have. 

The first commit contains the tests and that includes 3 variations on the bridge class BSiteUser, BSiteUserB, BSiteUserC.

The SiteUser class above should match BSiteUserB ... and this is the case where the @ManyToOne properties match the embedded id properties by property name (as opposed to by db column naming convention or by explicit use of @JoinColumn).

**Comment by rbygrave** [comment] 2016-03-23 04:12
And the last commit there is to adjust the test to run on Postgres (can not use 'user' as the db column name).

**Closed** 2016-03-23 05:02 UTC
Labels: bug

**Comment by ksperling** [comment] 2016-03-30 04:04
Works great, thanks!
