### ISSUE TITLE
JSONB object with NULL reference serialisation - NullPointer exception

### ISSUE THREAD

**Issue by rchincho** [ebean-orm/avaje-ebeanorm#597] opened 2016-03-13 19:53 UTC
Database - postgresql
Cache - Memcache
Framework - Play2.4

Fields-

```
@DbJsonB
private JsonNode items;
@DbJsonB
private JsonNode calculation;

setter & getter methods
```

Custom serialization

```
private void writeObject(ObjectOutputStream out) throws IOException {
        //out.defaultWriteObject();
        if(getItems() == null){
            out.writeBoolean(false);
        } else {
            out.writeBoolean(true);
            new ObjectMapper().configure(JsonGenerator.Feature.AUTO_CLOSE_TARGET, false).writeValue(out, items);
        }

       if(getCalculation() == null){
            out.writeBoolean(false);
        } else {
            out.writeBoolean(true);
            new ObjectMapper().configure(JsonGenerator.Feature.AUTO_CLOSE_TARGET, false).writeValue(out, calculation);
        }


    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        //in.defaultReadObject();
        if(in.readBoolean()){
            this.setItems(new ObjectMapper().configure(JsonParser.Feature.AUTO_CLOSE_SOURCE, false).readValue(in, JsonNode.class));
        }


        if(in.readBoolean()){
            this.setCalculation(new ObjectMapper().configure(JsonParser.Feature.AUTO_CLOSE_SOURCE, false).readValue(in, JsonNode.class));
        }


    }
```

This throwing exception while storing in memcache. Its because of lazy loading of NULL objects. Its working fine NOT Null jsonb objects

Exception
2016-03-14 00:55:01,614 - [DEBUG] - org.avaje.ebean.TXN - txn[1005] Commit
2016-03-14 00:55:01,667 - [ERROR] - play.core.server.netty.PlayDefaultUpstreamHandler - Cannot invoke the action
java.lang.NullPointerException: null
at com.avaje.ebeaninternal.server.core.DefaultBeanLoader.refreshBeanInternal(DefaultBeanLoader.java:379) ~[avaje-ebeanorm-6.8.1.jar:na]
at com.avaje.ebeaninternal.server.core.DefaultBeanLoader.refreshBeanInternal(DefaultBeanLoader.java:392) ~[avaje-ebeanorm-6.8.1.jar:na]
at com.avaje.ebeaninternal.server.core.DefaultBeanLoader.loadBean(DefaultBeanLoader.java:374) ~[avaje-ebeanorm-6.8.1.jar:na]
at com.avaje.ebeaninternal.server.core.DefaultServer.loadBean(DefaultServer.java:512) ~[avaje-ebeanorm-6.8.1.jar:na]
at com.avaje.ebean.bean.EntityBeanIntercept.loadBeanInternal(EntityBeanIntercept.java:751) ~[avaje-ebeanorm-6.8.1.jar:na]
at com.avaje.ebean.bean.EntityBeanIntercept.loadBean(EntityBeanIntercept.java:716) ~[avaje-ebeanorm-6.8.1.jar:na]
at com.avaje.ebean.bean.EntityBeanIntercept.preGetter(EntityBeanIntercept.java:811) ~[avaje-ebeanorm-6.8.1.jar:na]
at com.htr.desque.models.EstimateJsonData._ebean_get_calculation(EstimateJsonData.java:6) ~[classes/:na]
at com.htr.desque.models.EstimateJsonData.getCalculation(EstimateJsonData.java:36) ~[classes/:na]
at com.htr.desque.models.EstimateJsonData.writeObject(EstimateJsonData.java:52) ~[classes/:na]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_51]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_51]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_51]
at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_51]
at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:988) ~[na:1.8.0_51]
at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496) ~[na:1.8.0_51]
at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432) ~[na:1.8.0_51]
at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178) ~[na:1.8.0_51]
at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548) ~[na:1.8.0_51]
at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509) ~[na:1.8.0_51]
at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432) ~[na:1.8.0_51]
at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178) ~[na:1.8.0_51]
at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348) ~[na:1.8.0_51]
at com.github.mumoshu.play2.memcached.CustomSerializing.serialize(CustomSerializing.scala:24) ~[play2-memcached-play24_2.11-0.7.0.jar:0.7.0]
at net.spy.memcached.transcoders.SerializingTranscoder.encode(SerializingTranscoder.java:162) ~[spymemcached-2.9.0.jar:2.9.0]
at net.spy.memcached.MemcachedClient.asyncStore(MemcachedClient.java:291) ~[spymemcached-2.9.0.jar:2.9.0]
at net.spy.memcached.MemcachedClient.set(MemcachedClient.java:807) ~[spymemcached-2.9.0.jar:2.9.0]
at com.github.mumoshu.play2.memcached.MemcachedCacheApi.set(MemcachedCacheApi.scala:73) ~[play2-memcached-play24_2.11-0.7.0.jar:0.7.0]
at play.cache.DefaultCacheApi.set(DefaultCacheApi.java:43) ~[play-cache_2.11-2.4.6.jar:2.4.6]
at play.cache.Cache.set(Cache.java:52) ~[play-cache_2.11-2.4.6.jar:2.4.6]
at com.htr.framework.cache.CachedFinder.put(CachedFinder.java:143) ~[classes/:na]
at com.htr.framework.dao.CachedDAO.create(CachedDAO.java:32) ~[classes/:na]
at com.htr.desque.service.impl.EstimateServiceImpl.createEsitmate(EstimateServiceImpl.java:62) ~[classes/:na]
at com.htr.desque.controllers.EstimateAPI.addEstimate(EstimateAPI.java:54) ~[classes/:na]
at api.Routes$$anonfun$routes$1$$anonfun$applyOrElse$31$$anonfun$apply$157.apply(Routes.scala:828) ~[classes/:na]
at api.Routes$$anonfun$routes$1$$anonfun$applyOrElse$31$$anonfun$apply$157.apply(Routes.scala:828) ~[classes/:na]
at play.core.routing.HandlerInvokerFactory$$anon$4.resultCall(HandlerInvoker.scala:136) ~[play_2.11-2.4.6.jar:2.4.6]
at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$14$$anon$3$$anon$1.invocation(HandlerInvoker.scala:127) ~[play_2.11-2.4.6.jar:2.4.6]
at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:70) ~[play_2.11-2.4.6.jar:2.4.6]
at play.GlobalSettings$1.call(GlobalSettings.java:67) ~[play_2.11-2.4.6.jar:2.4.6]
at be.objectify.deadbolt.java.actions.AbstractSubjectAction$SubjectTest.lambda$null$15(AbstractSubjectAction.java:120) ~[deadbolt-java_2.11-2.4.3.jar:2.4.3]
at be.objectify.deadbolt.java.actions.AbstractSubjectAction$SubjectTest$$Lambda$61/440481247.apply(Unknown Source) ~[na:na]
at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:106) ~[play_2.11-2.4.6.jar:2.4.6]
at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:106) ~[play_2.11-2.4.6.jar:2.4.6]
at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251) [scala-library-2.11.7.jar:na]
at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249) [scala-library-2.11.7.jar:na]
at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library-2.11.7.jar:na]
at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40) [play_2.11-2.4.6.jar:2.4.6]
at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) [akka-actor_2.11-2.3.13.jar:na]
at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.11-2.3.13.jar:na]
at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.7.jar:na]
at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.7.jar:na]
at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.7.jar:na]
at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.7.jar:na]
2016-03-14 00:55:01,711 - [ERROR] - Global - Exception - /api/estimate - IP - 127.0.0.1
java.lang.NullPointerException: null
at com.avaje.ebeaninternal.server.core.DefaultBeanLoader.refreshBeanInternal(DefaultBeanLoader.java:379) ~[avaje-ebeanorm-6.8.1.jar:na]
at com.avaje.ebeaninternal.server.core.DefaultBeanLoader.refreshBeanInternal(DefaultBeanLoader.java:392) ~[avaje-ebeanorm-6.8.1.jar:na]
at com.avaje.ebeaninternal.server.core.DefaultBeanLoader.loadBean(DefaultBeanLoader.java:374) ~[avaje-ebeanorm-6.8.1.jar:na]
at com.avaje.ebeaninternal.server.core.DefaultServer.loadBean(DefaultServer.java:512) ~[avaje-ebeanorm-6.8.1.jar:na]
at com.avaje.ebean.bean.EntityBeanIntercept.loadBeanInternal(EntityBeanIntercept.java:751) ~[avaje-ebeanorm-6.8.1.jar:na]
at com.avaje.ebean.bean.EntityBeanIntercept.loadBean(EntityBeanIntercept.java:716) ~[avaje-ebeanorm-6.8.1.jar:na]
at com.avaje.ebean.bean.EntityBeanIntercept.preGetter(EntityBeanIntercept.java:811) ~[avaje-ebeanorm-6.8.1.jar:na]
at com.htr.desque.models.EstimateJsonData._ebean_get_calculation(EstimateJsonData.java:6) ~[classes/:na]
at com.htr.desque.models.EstimateJsonData.getCalculation(EstimateJsonData.java:36) ~[classes/:na]
at com.htr.desque.models.EstimateJsonData.writeObject(EstimateJsonData.java:52) ~[classes/:na]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_51]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_51]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_51]
at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_51]
at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:988) ~[na:1.8.0_51]
at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496) ~[na:1.8.0_51]
at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432) ~[na:1.8.0_51]
at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178) ~[na:1.8.0_51]
at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548) ~[na:1.8.0_51]
at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509) ~[na:1.8.0_51]
at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432) ~[na:1.8.0_51]
at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178) ~[na:1.8.0_51]
at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348) ~[na:1.8.0_51]
at com.github.mumoshu.play2.memcached.CustomSerializing.serialize(CustomSerializing.scala:24) ~[play2-memcached-play24_2.11-0.7.0.jar:0.7.0]
at net.spy.memcached.transcoders.SerializingTranscoder.encode(SerializingTranscoder.java:162) ~[spymemcached-2.9.0.jar:2.9.0]
at net.spy.memcached.MemcachedClient.asyncStore(MemcachedClient.java:291) ~[spymemcached-2.9.0.jar:2.9.0]
at net.spy.memcached.MemcachedClient.set(MemcachedClient.java:807) ~[spymemcached-2.9.0.jar:2.9.0]
at com.github.mumoshu.play2.memcached.MemcachedCacheApi.set(MemcachedCacheApi.scala:73) ~[play2-memcached-play24_2.11-0.7.0.jar:0.7.0]
at play.cache.DefaultCacheApi.set(DefaultCacheApi.java:43) ~[play-cache_2.11-2.4.6.jar:2.4.6]
at play.cache.Cache.set(Cache.java:52) ~[play-cache_2.11-2.4.6.jar:2.4.6]
at com.htr.framework.cache.CachedFinder.put(CachedFinder.java:143) ~[classes/:na]
at com.htr.framework.dao.CachedDAO.create(CachedDAO.java:32) ~[classes/:na]
at com.htr.desque.service.impl.EstimateServiceImpl.createEsitmate(EstimateServiceImpl.java:62) ~[classes/:na]
at com.htr.desque.controllers.EstimateAPI.addEstimate(EstimateAPI.java:54) ~[classes/:na]
at api.Routes$$anonfun$routes$1$$anonfun$applyOrElse$31$$anonfun$apply$157.apply(Routes.scala:828) ~[classes/:na]
at api.Routes$$anonfun$routes$1$$anonfun$applyOrElse$31$$anonfun$apply$157.apply(Routes.scala:828) ~[classes/:na]
at play.core.routing.HandlerInvokerFactory$$anon$4.resultCall(HandlerInvoker.scala:136) ~[play_2.11-2.4.6.jar:2.4.6]
at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$14$$anon$3$$anon$1.invocation(HandlerInvoker.scala:127) ~[play_2.11-2.4.6.jar:2.4.6]
at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:70) ~[play_2.11-2.4.6.jar:2.4.6]
at play.GlobalSettings$1.call(GlobalSettings.java:67) ~[play_2.11-2.4.6.jar:2.4.6]
at be.objectify.deadbolt.java.actions.AbstractSubjectAction$SubjectTest.lambda$null$15(AbstractSubjectAction.java:120) ~[deadbolt-java_2.11-2.4.3.jar:2.4.3]
at be.objectify.deadbolt.java.actions.AbstractSubjectAction$SubjectTest$$Lambda$61/440481247.apply(Unknown Source) ~[na:na]
at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:106) ~[play_2.11-2.4.6.jar:2.4.6]
at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:106) ~[play_2.11-2.4.6.jar:2.4.6]
at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251) [scala-library-2.11.7.jar:na]
at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249) [scala-library-2.11.7.jar:na]
at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library-2.11.7.jar:na]
at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40) [play_2.11-2.4.6.jar:2.4.6]
at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) [akka-actor_2.11-2.3.13.jar:na]
at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.11-2.3.13.jar:na]
at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.7.jar:na]
at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.7.jar:na]
at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.7.jar:na]
at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.7.jar:na]

**Comment by rbygrave** [comment] 2016-03-13 21:57
I'll close this as it appears to be a duplicate of https://github.com/ebean-orm/avaje-ebeanorm/issues/598

**Closed by rbygrave** 2016-03-13 21:57 UTC
