### ISSUE TITLE
ExplicitJdbcTransaction leaves dangling “begin”

### ISSUE THREAD

**Issue by dastultz** [ebean-orm/avaje-ebeanorm#524] opened 2016-01-08 18:51 UTC
Hi Rob,

This issue is preventing me from upgrading to Ebean 6. It would be super if we could get this fixed as it would mean an end to all the wacky transaction trickery I’ve had to do to support auto commit in both true and false forms.

My JDBC and OpenJPA work requires auto commit true (I’ll call this ACT). Earlier Ebean requires it false (ACF). I had a little trickery in my data source that would flip it to ACF before giving the connection to Ebean (unless I was already in a transaction). This was working but not ideal.

`JdbcTransaction` has `performRollback` and `performCommit` but no `performBegin` to start a transaction. Instead it appears `checkAutoCommit` has been “repurposed” to start the transaction. With ACF you can select all day, no problem. As soon as you insert/update/delete you have to commit. There’s essentially always one implicit transaction. With ACT you need to issue the query “begin” when a transaction is to be started. This is presently done in `checkAutoCommit`.

The problem with this is when there is no explicit transaction and only “select” statements are issued, the “begin” query is not matched by any “commit” or “rollback”. This doesn’t seem to be a huge problem in general but it is causing a weird hang up when I pair a couple unit tests together. I have an update method that hangs forever. Not likely reproducible in an independent unit test.

My thinking is that `JdbcTransaction` needs a `performBegin` or some such that is called only when a transaction is to be started (implicit or explicit). Any subclass that uses ACF would do nothing while `ExplicitJdbcTransaction` would issue “begin”. `ExplicitJdbcTransaction.checkAutoCommit` should simply verify that auto commit is true.

What do you think?

**Comment by rbygrave** [comment] 2016-01-10 23:02
> The problem with this is when there is no explicit transaction and only “select” statements are issued, the “begin” query is not matched by any “commit” or “rollback”. 

This somewhat specific to Postgres and Oracle (MVCC databases that I trust with read committed isolation level). Specifically in your case you are using PostgresPlatform and that has onQueryOnly = OnQueryOnly.CLOSE (rather than ROLLBACK or COMMIT).

If you look/breakpoint at TransactionManager.initOnQueryOnly() you will see this value checked against the isolation level etc and here it also allows explicit setting via system property.

```java
String systemPropertyValue = System.getProperty("ebean.transaction.onqueryonly");
```

Now the reason this is like this generally is because usually "begin transaction" is implicit ... however, in the case of using ExplicitJdbcTransaction the "begin transaction" is no longer implicit but instead executes the "begin" statement.

So I believe what you are experiencing is that via ExplicitJdbcTransaction you get explicit "begin" executed but via onQueryOnly=OnQueryOnly.CLOSE ... we are not seeing effective closing of the transaction in the query only cases.
 
So to confirm the theory set system property via:
```java
System.setProperty("ebean.transaction.onqueryonly", "COMMIT"); // or ROLLBACK if you like
```
... and run the tests again.

**Comment by rbygrave** [comment] 2016-01-11 01:05
I have pushed up an expected fix for this issue.  Daryl, if you get a chance to review and perhaps test that would be great.

**Comment by dastultz** [comment] 2016-01-11 15:06
Setting the system property `ebean.transaction.onqueryonly` to either COMMIT or ROLLBACK gets me past the weird hanging problem. The begins that were dangling are now matched with commit/rollback. It looks like I need to use "COMMIT" in order manage my transactions in JDBC.

I can't build Ebean. It fails on what looks like a bunch of `java.time` stuff and ... we're still on Java 6. It looks like you are simply choosing ROLLBACK instead of CLOSE. It seems fine, but since I need COMMIT, it won't serve me in the end. Still, if you send me a built snapshot I can test that it gets past my hanging test.

For a bunch of select-only queries, would you say the begins/commits that wrap them are going to cost me a performance hit?

**Comment by rbygrave** [comment] 2016-01-11 19:35
> but since I need COMMIT, it won't serve me in the end. 

I can change it to use COMMIT, no problem there.

> For a bunch of select-only queries, would you say the begins/commits that wrap them are going to cost me a performance hit?

Yes but that is ok.

**Comment by dastultz** [comment] 2016-01-11 20:00
Hi Rob, thanks for sending me the snapshot. It fixes the problem (when I remove `System.setProperty("ebean.transaction.onqueryonly", "COMMIT")`).

I looked at the source, and the comment still states "rollback" instead of "commit" as the override.

Regarding the performance hit, you say it's "OK". Does that mean it's "not too bad"? It's not worth the effort to remove all begin/commit statements for on-query-only?

Thanks.

**Comment by rbygrave** [comment] 2016-01-11 20:36
Cool, I'll fix that comment.

> It's not worth the effort to remove all begin/commit statements for on-query-only?

The performance hit is relative to the cost of the queries.  If all the transactions just had a single cheap query like (select singleColumn from table where primaryKey = ?) then the relative overhead is high and you should look into removing those "begin"s ... but if those transactions have multiple queries (more complex graphs) or more complex/normal queries then the relative cost is much lower.

So the answer regarding performance is that this would require some time/effort into benchmarking the difference ... but there is a plan for a dashboard and if we had that now we could better answer that (rather than just say "do benchmarking").

**Comment by dastultz** [comment] 2016-01-11 20:45
Ok, I'm not sure what you mean by "you should look into removing those
"begin"s" since those are issued by ExplicitJdbcTransaction. It seems to me
that neither begin/commit/rollback should be issued for OnQueryOnly.

**Comment by rbygrave** [comment] 2016-01-11 21:55
> you should look into removing those "begin"s" since those are issued by
ExplicitJdbcTransaction

Yes, it would be more accurate to say ... you could then move away
from ExplicitJdbcTransaction
to the standard approach.  Given that is pretty much an all or nothing (all
transactions or no transactions for a given EbeanServer instance) that is
unlikely to be an option for you.

**Closed** 2016-01-12 11:17 UTC
Labels: bug

**Comment by dastultz** [comment] 2016-01-14 20:35
This feature (`ExplicitJdbcTransaction`) does appear to do what it is intended to, certainly this issue of dangling begin is settled, but it does appear I can't use it. If I start a transaction in JDBC, the commit issued here does commit the transaction and a subsequent rollback does nothing. (Postgresql does not support nested transactions.)

I had suggested that for `OnQueryOnly` neither of begin or commit should be issued. If this were supported, I'd still have the issue with an "implicit" transaction - I start a Tx in JDBC, insert via Ebean (not in an Ebean Tx), issue a rollback in JDBC, the Tx is already committed by the implicit Tx Ebean creates for the insert.

I totally own all this transaction mixing nonsense, I'm simply not in a position to go "all Ebean". I will have to revert to the trickery I was doing before as it was in fact working. I don't know if you want to maintain `ExplicitJdbcTransaction` or remove it.

Sorry.

**Comment by rbygrave** [comment] 2016-01-14 22:00
Hmmm, bummer.

*> (Postgresql does not support nested transactions.)*

In JDBC I'd expect to create save points via
java.sql.Connection.setSavepoint() to achieve nested transactions - I'm not
surprised nested "begin" is insufficient.


*>  If this were supported, I'd still have the issue with an "implicit"
transaction - I start a Tx in JDBC, insert via Ebean (not in an Ebean Tx),
issue a rollback in JDBC, the Tx is already committed by the implicit Tx
Ebean creates for the insert.*

I'm not sure I follow this bit (external code starts the transaction but
Ebean also thinks it is implicit). I believe externally the transaction is
started (say with "begin") but then the java.sql.Connection is still in the
pool such that Ebean thinks it is implicit.

I'm looking at the
test com.avaje.tests.transaction.TestExplicitTransactionMode. If you wish
to modify or add to that test to reproduce I'm happy to have a look there.

I presume you have investigated the impact of changing to use the methods
on EbeanServer that take a Transaction. In that case there is no implicit
transaction, Ebean will not ever do an implicit commit or rollback etc.


*> I will have to revert to the trickery I was doing before as it was in
fact working. *

Ok. I am happy to keep looking at it a bit more and especially if we can
modify TestExplicitTransactionMode to match your scenario.


Cheers, Rob.

**Comment by dastultz** [comment] 2016-01-15 12:40
>
>
> In JDBC I'd expect to create save points via
> java.sql.Connection.setSavepoint() to achieve nested transactions


That's interesting, I could look into intercepting begin/commit from Ebean
when in a JDBC transaction and either redirecting to save point logic or
ignoring altogether. So don't remove this feature yet. :-)

>
>
> I'm looking at the
> test com.avaje.tests.transaction.TestExplicitTransactionMode. If you wish
> to modify or add to that test to reproduce I'm happy to have a look there.
>

I'll take a look but it doesn't build for me so that might be tough.

>
> I presume you have investigated the impact of changing to use the methods
> on EbeanServer that take a Transaction.


Yes, the challenge is that I have a lot of existing code that would all
need to be reworked. I can't just plug in a Transaction Manager to the
Ebean Server at a high level.

/D

**Comment by dastultz** [comment] 2016-01-15 17:41
I've decided to produce a `DoNothingPreparedStatement` when my JDBC connection is already in a transaction and Ebean wants to issue begin, commit, or rollback. There might be a corner case that is problematic, but I've got pretty good unit test coverage of various transaction patterns involving JDBC, Ebean and OpenJPA. So far it's working. (Please keep `ExplicitJdbcTransaction`. :-) )
