### ISSUE TITLE
ENH: Ability to add new ScalarType without touching the rest of Ebean framework

### ISSUE THREAD

**Issue by mutovkin** [ebean-orm/avaje-ebeanorm#571] opened 2016-02-22 15:09 UTC
I would like to add a new Scalar type support PostgreSQL specific type - Enum (in my case existing tables already use this type).
http://www.postgresql.org/docs/current/static/datatype-enum.html
I've looked at how other types are implemented - it seems that if I were to implement I would I have to add a new annotation, then type class itself and ability to set . Am I right that at this point there is no way to add (register) 3rd party types without changing the rest of Ebean framework (i.e. continue using 6.8.1 version that is currently default version for Play 2.4 and have new type defined in my project)? If I'm right I think it would be great to have such registration mechanism without need to ask to support this and that type right in the Ebean framework.

**Comment by rbygrave** [comment] 2016-02-25 19:45
Yes this is a good idea / feature request. I won't get to it in the next 2 weeks but hopefully not to long after that.

Cheers, Rob.

**Comment by rbygrave** [comment] 2016-04-22 05:16
Ok, I'm reviewing this issue and having second thoughts about it.

The Postgres Enum type is not a particularly good example.  Ignoring the DDL aspect is can be supported by an Enum mapping to string values.  If the plan is to include DDL generation support then it gets a lot more complex and for this type I don't see the big value to offset that complexity.

>  it seems that if I were to implement I would I have to add a new annotation, then type class itself and ability to set .

Generally ScalarType's don't need an annotation (think URL, URI, Locale, UUID etc) where their type maps to a single DB type.  We need annotations when those types have different mapping options (like @DbJson).

Simple ScalarTypes that map to an existing standard DB type (varchar etc) are pretty straight forward but types that need special support for DDL are different.

Can you confirm exactly what you are looking for here?  

Thanks, Rob.

**Comment by rbygrave** [comment] 2016-05-06 05:12
I think we should close this issue.  Note that you can already register a custom ScalarType via ServerConfig.addClass() ... or alternatively a ScalarType can be found automatically via classpath scanning (if classpath scanning is used to find entity beans etc).

However, this really only works on relatively simple types and doesn't really work when the scalar type has implications for DDL generation (and DB migration) such as the Postgres types - ARRAY, JSON, JSONB and HSTORE.  With these we really need other Ebean internals to support the specific JDBC and DDL for these types.

So I think we will close this for now (no planned action) and revisit on demand.

Cheers, Rob.

**Closed by rbygrave** 2016-05-06 05:12 UTC
Labels: enhancement

**Comment by kny78** [comment] 2019-08-07 07:31
Sorry for a late response to this, but I also have the need.

Our usecase is:
   1. We have an existing database, where PostgreSQL native Enums have is in use.
   2. We would like to keep the enums, as they define the data more strictly and precisely.

* The issue is that it tries to store it as "varchar", while we should be able to either override the datatype when persisting, or not defining the datatype. 
   ** Not defining the datatype, it should default to implicit casts.
* DDL generation from Java code is not a specific need here.

**Comment by rbygrave** [comment] 2019-08-07 08:16
@kny78  Provide an example in JDBC of what you are looking to do / need.

**Comment by kny78** [comment] 2019-08-07 12:43
I created a small example-project (based on play's samples):
https://github.com/kny78/poc-play-ebean-pg-enum

I run in SBT:
```testOnly models.ExampleEntityTest```

Then I get the error:
```
Caused by: org.postgresql.util.PSQLException: ERROR: column "my_enum" is of type my_enum_type but expression is of type character varying
```
A pure insert in PostgreSQL (psql) gives me these:
```
test=# insert into test (my_str, my_enum) VALUES('from psql cmd', 'VAL_1');
INSERT 0 1
test=# insert into test (my_str, my_enum) VALUES('from psql cmd', 'VAL_1'::my_enum_type);
INSERT 0 1
test=# insert into test (my_str, my_enum) VALUES('from psql cmd', 'VAL_1'::varchar);
ERROR:  column "my_enum" is of type my_enum_type but expression is of type character varying
LINE 1: ...to test (my_str, my_enum) VALUES('from psql cmd', 'VAL_1'::v...
                                                             ^
HINT:  You will need to rewrite or cast the expression.
```


So if I could set "dbtype" like for example:
```
@DbEnumValue(dbtype="my_enum_type")
```

Then it would be all good :-D

**Comment by rbygrave** [comment] 2019-08-07 21:27
Right.  I'm kind of looking for Postgres JDBC that binds via `PGobject`.

There is io.ebeaninternal.server.type.PostgresHelper with methods `asInet()` and `asObject()` which Ebean uses for `json`, `jsonb` and `inet` types.

Is there a similar way to use `PGobject` for binding an enum?   That would mean we bind using `PGobject` and don't do the cast in sql which would be my preference.  Is that an option?

**Comment by rbygrave** [comment] 2019-08-07 21:34
Maybe https://www.programcreek.com/java-api-examples/?code=JadiraOrg/jadira/jadira-master/usertype.core/src/main/java/org/jadira/usertype/corejava/enumerated/PersistentEnumAsPostgreSQLEnum.java

**Comment by kny78** [comment] 2019-08-08 04:34
God morning,

PGObject seems like the correct way to bind a custom object to a
prepared statement.I did a quick test on the example code, and it seems
to persist it correctly :-)

-Kjetil
On Wed, 2019-08-07 at 14:27 -0700, Rob Bygrave wrote:
> Right.  I'm kind of looking for Postgres JDBC that binds via
> PGobject.
> 
> There is io.ebeaninternal.server.type.PostgresHelper with methods
> asInet() and asObject() which Ebean uses for json, jsonb and inet
> types.
> 
> Is there a similar way to use PGobject for binding an enum?   That
> would mean we bind using PGobject and don't do the cast in sql which
> would be my preference.  Is that an option?
> 
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 
> [
> {
> "@context": "http://schema.org",
> "@type": "EmailMessage",
> "potentialAction": {
> "@type": "ViewAction",
> "target": "
> https://github.com/ebean-orm/ebean/issues/571?email_source=notifications\u0026email_token=AAFYG6NPVMK4UVJTOK22MULQDM443A5CNFSM4B36R5U2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3ZYH4Y#issuecomment-519275507
> ",
> "url": "
> https://github.com/ebean-orm/ebean/issues/571?email_source=notifications\u0026email_token=AAFYG6NPVMK4UVJTOK22MULQDM443A5CNFSM4B36R5U2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3ZYH4Y#issuecomment-519275507
> ",
> "name": "View Issue"
> },
> "description": "View this Issue on GitHub",
> "publisher": {
> "@type": "Organization",
> "name": "GitHub",
> "url": "https://github.com"
> }
> }
> ]
-- 
Kjetil Nygård
pulk.hesten@gmail.com
Tlf +47 4147 4337

**Comment by mutovkin** [comment] 2019-11-15 06:30
@kny78 Can you please update your repository with an example of how you managed to persist enum. I've returned to this problem after several years and still can't find a way to do it with eBean.

**Comment by mutovkin** [comment] 2019-11-15 07:56
@rbygrave Am I on the right path to create generic Enum scalar type:
https://gist.github.com/mutovkin/ba014557d2e2fb5c0095d76b1262faff

If so how do I register it?
