### ISSUE TITLE
NPE because ServerConfig.properties is null

### ISSUE THREAD

**Issue by greenlaw110** [ebean-orm/avaje-ebeanorm#408] opened 2015-09-06 23:41 UTC
![image](https://cloud.githubusercontent.com/assets/216930/9707246/8625eca0-5544-11e5-919c-80b1938bc771.png)

**Comment by rbygrave** [comment] 2015-09-07 02:06
Firstly note that when tickets with errors are logged they should contain the stack trace.  It is important to contain the stack trace as that helps searching later (google etc).

For this issue,  it is a duplicate of https://github.com/ebean-orm/avaje-ebeanorm/issues/401.

So I'll close it as a duplicate.

Thanks, Rob.

**Closed by rbygrave** 2015-09-07 02:06 UTC
