### ISSUE TITLE
Missing property from class extended @MappedSuperclass with maven module as dependency

### ISSUE THREAD

**Issue by dtelaroli** [ebean-orm/avaje-ebeanorm#200] opened 2014-11-13 18:01 UTC
The Ebean does not found Entity property id in the @MappedSuperclass when it's into a maven module as dependency, otherwise, if the Entity is on the same module work fine.

The property was found by reflection, but by the enhancement plugin not was found.

```
java.lang.ExceptionInInitializerError
	at org.dtelaroli.cms.domain.model.UserTest.schema(UserTest.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.IllegalStateException: Property id not found in [email, password, confirm, active, roles]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.setBeanReflect(BeanDescriptorManager.java:1309)
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.createByteCode(BeanDescriptorManager.java:1134)
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.readDeployAssociations(BeanDescriptorManager.java:1050)
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.readEntityDeploymentAssociations(BeanDescriptorManager.java:529)
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.deploy(BeanDescriptorManager.java:241)
	at com.avaje.ebeaninternal.server.core.InternalConfiguration.<init>(InternalConfiguration.java:116)
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:185)
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:106)
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:46)
	at com.avaje.ebean.EbeanServerFactory.create(EbeanServerFactory.java:37)
	at com.avaje.ebean.Ebean$ServerManager.getWithCreate(Ebean.java:206)
	at com.avaje.ebean.Ebean$ServerManager.<init>(Ebean.java:162)
	at com.avaje.ebean.Ebean$ServerManager.<init>(Ebean.java:128)
	at com.avaje.ebean.Ebean.<clinit>(Ebean.java:122)
	... 25 more

```

**Comment by someok** [comment] 2015-01-14 11:59
I also have this problem, so I still use avaje-ebeanorm-agent-4.1.2.jar.

**Comment by rbygrave** [comment] 2015-08-31 02:56
This is specifically an issue with the maven plugin and not with the agent per say.  

I have reproduced this in 4.5.1 and confirmed it is fixed in 4.6.1 (and 4.7.1).

So yes, sorry that has taken so long to get this resolved but yes fixed in 4.6.1 (and 4.7.1).

**Closed by rbygrave** 2015-08-31 02:56 UTC
Labels: bug

**Comment by rbygrave** [comment] 2015-08-31 03:01
Fixed in avaje-ebeanorm-mavenenhancer version 4.6.1 (and 4.7.1).

**Comment by dtelaroli** [comment] 2015-09-04 02:23
Thanks


Abraço,
Denilson Telaroli.

2015-08-31 0:01 GMT-03:00 Rob Bygrave <notifications@github.com>:

**Comment by ChNan** [comment] 2017-10-14 15:36
hi ,this bug reproduce again.

Dev tool: IDEA Intellij 2016.3

Plugin:  enhancement 10.x

it's maven project.

Module A  dependency Module B

BaseEntity is in Module B
User is in Module A

--------------------------------------------------------------------------------------------
Caused by: java.lang.IllegalStateException: Property id not found in [name, email] for type class com.tbfreelancer.ms.user.modules.user.entity.User
	at io.ebeaninternal.server.deploy.BeanDescriptorManager.setBeanReflect(BeanDescriptorManager.java:1335)
	at io.ebeaninternal.server.deploy.BeanDescriptorManager.createByteCode(BeanDescriptorManager.java:1291)
	at io.ebeaninternal.server.deploy.BeanDescriptorManager.readDeployAssociations(BeanDescriptorManager.java:1209)
	at io.ebeaninternal.server.deploy.BeanDescriptorManager.readEntityDeploymentAssociations(BeanDescriptorManager.java:712)
	at io.ebeaninternal.server.deploy.BeanDescriptorManager.deploy(BeanDescriptorManager.java:320)
	at io.ebeaninternal.server.core.InternalConfiguration.<init>(InternalConfiguration.java:141)

**Comment by sjaanus** [comment] 2022-05-24 10:19
@xyyzzzz were you ever able to solve it?
