### ISSUE TITLE
Not-trimmed values in configuration properties

### ISSUE THREAD

**Issue by dspasibenko** [ebean-orm/avaje-ebeanorm#234] opened 2015-01-22 02:55 UTC
I edited ebean.properties and accidentally added a space at tail of the following line:

datasource.pg.databaseDriver=org.postgresql.Driver 

EBean stopped to work and reported that error as: 
Caused by: java.lang.ClassNotFoundException: org.postgresql.Driver 
...
It was not so easy to catch the root cause and found that there is an unpleasant space in the property value. I think it is good idea to trim some property values whenever it makes sense.

**Comment by rbygrave** [comment] 2015-01-29 09:33
Can you confirm the version of Ebean you are using as I am unable to reproduce.  

That is, the properties loading mechanism already trims the values. PropertiesWrapper is used internally in DataSourceConfig ... and that trims the values.  

It might be you are using an older version of Ebean.

**Comment by rbygrave** [comment] 2015-02-02 07:41
I'll close this for now.  We can reopen if the issue can reproduce in the latest version of Ebean.

Thanks, Rob.

**Closed by rbygrave** 2015-02-02 07:41 UTC
