### ISSUE TITLE
[@SoftDelete]db.delete()  cannot syncing data to Elasticsearch when use "@softDelete

### ISSUE THREAD

**Issue by duishancunzhang** [ebean-orm/avaje-ebeanorm#774] opened 2016-07-14 03:29 UTC
my meet an error is :
when invoke SoftDelete,[mysql] execute "update" operation after that [ElasticSearch] followed it,do a "update bulk".
But i am glad to see [ElasticSearch] can receive a "delete bulk" request.

**Comment by rbygrave** [comment] 2016-07-27 04:25
As I see it this is a duplicate of https://github.com/ebean-orm/avaje-ebeanorm-elastic/issues/12

We should probably close this issue and process the other one.

**Comment by rbygrave** [comment] 2016-07-28 05:41
Closing this, will look to progress ebean-orm/avaje-ebeanorm-elastic#12

**Closed by rbygrave** 2016-07-28 05:41 UTC
Labels: duplicate

**Comment by duishancunzhang** [comment] 2016-07-28 07:35
got it ，thanks very much!
